# PULL THE BASE IMAGE
FROM python:3.10.12-slim-buster

## SET ENVIRONMENT VARIABLES
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code
COPY requirements.txt .

# INSTALL DEPENDENCIES
RUN pip install -r requirements.txt

# COPY PROJECT
COPY . .
